<?xml version="1.0"?>
 <robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
 <!-- Put here the robot description -->
 <xacro:property name="PI" value="3.1415926535897931"/>
 <xacro:property name="chassisHeight" value="0.1"/>
 <xacro:property name="chassisLength" value="0.4"/>
 <xacro:property name="chassisWidth" value="0.2"/>
 <xacro:property name="chassisMass" value="50"/>
 <xacro:property name="casterRadius" value="0.05"/>
 <xacro:property name="casterMass" value="5"/>
 <xacro:property name="wheelWidth" value="0.05"/>
 <xacro:property name="wheelRadius" value="0.1"/>
 <xacro:property name="wheelPos" value="0.2"/>
 <xacro:property name="wheelMass" value="5"/>
 <xacro:property name="cameraSize" value="0.05"/>
 <xacro:property name="cameraMass" value="0.1"/>
 <xacro:property name="imuSize" value="0.001"/>
 <xacro:property name="imuMass" value="0.01"/>
 <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
 <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
 <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

 <link name="footprint" />
 <joint name="base_joint" type="fixed">
  <parent link="footprint"/>
  <child link="chassis"/>
 </joint>
 <link name='chassis'>
  <collision>
   <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
   <geometry>
    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
   </geometry>
  </collision>
  <visual>
   <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
   <geometry>
    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
   </geometry>
   <material name="blue"/>
  </visual>
  <inertial>
   <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
   <mass value="${chassisMass}"/>
   <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
  </inertial>
 </link>
 <joint name="fixed" type="fixed">
  <parent link="chassis"/>
  <child link="caster_wheel"/>
 </joint>
 <link name="caster_wheel">
  <collision>
   <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
   <geometry>
    <sphere radius="${casterRadius}"/>
   </geometry>
  </collision>
  <visual>
   <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
   <geometry>
    <sphere radius="${casterRadius}"/>
   </geometry>
   <material name="red"/>
  </visual>
  <inertial>
   <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
   <mass value="${casterMass}"/>
   <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
 </link>
 <wheel lr="left" tY="1"/>
 <wheel lr="right" tY="-1"/>
 <joint name="imu_joint" type="continuous">
  <parent link="chassis"/>
  <child link="imu"/>
 <origin xyz="0 0 ${chassisHeight+wheelRadius}" rpy="0 0 0" />
  <axis xyz="0 0 0" rpy="0 0 0" />
  <limit effort="0" velocity="0"/>
  <joint_properties damping="0.0" friction="0.0"/>
 </joint>
 <link name="imu">
  <collision>
   <origin xyz="0 0 0" rpy="0 0 0"/>
   <geometry>
    <box size="${imuSize} ${imuSize} ${imuSize}"/>
   </geometry>
  </collision>
  <visual>
   <origin xyz="0 0 0" rpy="0 0 0"/>
   <geometry>
    <box size="${imuSize} ${imuSize} ${imuSize}"/>
   </geometry>
   <material name="blue"/>
  </visual>
  <inertial>
   <mass value="${imuMass}" />
   <origin xyz="0 0 0" rpy="0 0 0"/>
   <box_inertia m="${imuMass}" x="${imuSize}" y="${imuSize}" z="${imuSize}" />
  </inertial>
 </link>
</robot>
